# create containers for the backend and frontend services
services:
  backend:
    image: template-backend
    build: ./packages/backend
    ports:
      - "5000:5000"
    env_file:
      - ./packages/backend.env
  
  frontend:
    image: template-frontend
    build: ./packages/frontend
    ports:
      - "80:3000"
    env_file:
      - ./packages/frontend/.env
    depends_on:
      - backend
