apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-backend
  labels:
    app: template
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template
      component: backend
  template:
    metadata:
      labels:
        app: template
        component: backend
    spec:
      containers:
        - name: backend
          image: thisoliver/template:backend
          imagePullPolicy: Always
          env:
            - name: BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: template
                  key: BUCKET_NAME

            - name: BUCKET_S3_REGION
              valueFrom:
                secretKeyRef:
                  name: template
                  key: BUCKET_S3_REGION

            - name: BUCKET_S3_URI
              valueFrom:
                secretKeyRef:
                  name: template
                  key: BUCKET_S3_URI

            - name: BUCKET_S3_KEY
              valueFrom:
                secretKeyRef:
                  name: template
                  key: BUCKET_S3_KEY

            - name: BUCKET_S3_SECRET
              valueFrom:
                secretKeyRef:
                  name: template
                  key: BUCKET_S3_SECRET

            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: template
                  key: DB_URI

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: template
                  key: JWT_SECRET

            - name: ADMIN_SECRET
              valueFrom:
                secretKeyRef:
                  name: template
                  key: ADMIN_SECRET

            - name: ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: template
                  key: FRONTEND_ORIGIN

          ports:
            - containerPort: 5000
              name: backend-port
          resources:
            limits:
              memory: "256Mi"
              cpu: "0.5"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-frontend
  labels:
    app: template
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template
      component: frontend
  template:
    metadata:
      labels:
        app: template
        component: frontend
    spec:
      containers:
        - name: frontend
          image: thisoliver/template:frontend
          imagePullPolicy: Always
          env:
            - name: NUXT_PUBLIC_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: template
                  key: BACKEND_ORIGIN
          ports:
            - containerPort: 3000
              name: frontend-port
          resources:
            limits:
              memory: "256Mi"
              cpu: "0.5"
