apiVersion: v1
kind: Service
metadata:
  name: template-frontend
  labels:
    app: template
    component: frontend

spec:
  type: NodePort
  selector:
    app: template
    component: frontend

  ports:
    - protocol: TCP
      port: 80
      targetPort: frontend-port # <- frontend container port in deployment.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: template-backend
  labels:
    app: template
    component: backend

spec:
  type: NodePort
  selector:
    app: template
    component: backend

  ports:
    - protocol: TCP
      port: 5000
      targetPort: backend-port
