apiVersion: v1
kind: Service
metadata:
  name: template-client
  labels:
    app: template
    component: client

spec:
  type: NodePort
  selector:
    app: template
    component: client

  ports:
    - protocol: TCP
      port: 80
      targetPort: client-port # <- client container port in deployment.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: template-server
  labels:
    app: template
    component: server

spec:
  type: NodePort
  selector:
    app: template
    component: server

  ports:
    - protocol: TCP
      port: 5000
      targetPort: server-port
